import React from 'react';
import { Content } from '../Styles/sobre';
import Header from '../components/Head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const Sobre = () => {
    return ( 
        <div>
            <Header />
            <Navbar />
            <Content>
                <h1>Sobre Nós</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, cum. Nulla, laborum sapiente, illum debitis aliquam ducimus dolores porro dolorem blanditiis eligendi quis doloribus eum saepe tempora! Dignissimos pariatur cumque reprehenderit atque ad maiores repellat quas veniam, cum eos eligendi eveniet. Tempore quibusdam libero tempora placeat voluptates laudantium praesentium suscipit hic cum? Aut, suscipit animi at earum optio dolor enim quas rerum est deleniti ullam maiores sed! At consectetur iure accusamus? Perferendis magnam officiis, aut quasi mollitia repellendus eum voluptate sit! Consectetur minima nobis cumque esse. In nostrum rem voluptas perferendis qui cupiditate voluptate. Explicabo reiciendis, repellendus eveniet a repudiandae nemo quis illo error! Sequi iure assumenda, ea unde aliquam blanditiis perferendis aspernatur eius consectetur fugiat doloremque eum ad. Illo culpa amet reiciendis ratione perspiciatis aut molestiae aspernatur earum tempore. Quis exercitationem ea cupiditate accusantium quae sed dignissimos illo quo magnam tempore sunt eveniet, qui corporis numquam omnis explicabo. Ratione magni tenetur enim consectetur libero cupiditate atque accusamus animi est perferendis necessitatibus iure officiis tempora similique, quia laudantium dicta veniam nemo illum amet natus. Hic, nisi alias! At, quibusdam eius tempore placeat aliquid non sapiente. Impedit magni quibusdam officia pariatur, maiores adipisci illo aspernatur, ipsam, sint nemo temporibus quia magnam.</p>
                <h2>Lorem, ipsum dolor.</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam beatae reiciendis fugit, ab eveniet, quis molestiae corrupti hic necessitatibus dolorum esse earum provident dignissimos itaque ex tenetur accusamus debitis culpa reprehenderit numquam? Eveniet, laborum. Cum eaque esse fugiat ut maxime magnam deleniti fuga sint dolore voluptate, dolor tempora quam ipsam officiis corrupti quod a repudiandae veritatis et, eligendi dicta. Eveniet ratione esse impedit mollitia deleniti facilis ipsam magnam adipisci numquam saepe, beatae neque laudantium illo nisi eaque nemo nostrum? Repellat expedita iste quibusdam sit soluta molestias itaque provident adipisci autem quaerat dolorem laudantium nesciunt suscipit et, inventore, officia dolores asperiores ex repudiandae exercitationem temporibus at numquam, id vitae! Doloribus recusandae necessitatibus accusamus voluptate delectus esse atque suscipit officia temporibus architecto sunt aliquid sit nulla minus molestias nam porro, exercitationem illum sequi! Quis enim amet corrupti id, unde praesentium quas dolor sit animi expedita incidunt repudiandae tempore recusandae neque aspernatur suscipit, quasi pariatur. Doloribus aut harum deleniti a vero odit quo consequatur voluptatem assumenda! Esse rem quis suscipit porro adipisci eaque error iusto totam natus. Minus, culpa fuga! Sint eligendi deleniti dignissimos fugit accusantium vel at aspernatur recusandae! Aliquid illum inventore ullam alias ex quibusdam consequuntur, dolor ipsum magnam architecto aliquam quia, necessitatibus sit vitae debitis! Quasi inventore labore repudiandae placeat debitis voluptas blanditiis iusto delectus? Minima, nam quibusdam? Ut cumque ea hic consequatur corrupti temporibus harum fugit, neque asperiores, aperiam ratione quis laboriosam esse reprehenderit vitae deleniti commodi perspiciatis quos provident magnam ipsa odio pariatur, fuga tenetur. Optio animi reiciendis consectetur aspernatur magni. Nostrum corporis saepe aut quo delectus perferendis dolorum quidem esse eligendi magni eaque sunt dolorem doloribus tenetur cum ab perspiciatis veniam, et mollitia voluptatem. Dolorum nam molestiae sint fugit, porro maiores repudiandae qui saepe quibusdam quia, nostrum eaque hic temporibus perspiciatis praesentium consequuntur! Deleniti aut ullam totam?</p>
                <h2>Lorem, ipsum dolor.</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Explicabo, molestias earum. Numquam illum nesciunt deserunt! Quaerat, repellat. Error ipsa nisi explicabo odio corporis porro facere minus accusantium nostrum perferendis laudantium vero molestias, dolorem labore veniam aspernatur quis sunt a! Quidem eius nulla sit dicta ea, eveniet dolorum neque eum hic magnam fuga incidunt architecto, ratione sed voluptatibus ipsa et aperiam error aut delectus blanditiis ab aspernatur maiores molestias. Quasi maiores modi ipsa amet, atque odio! Iusto corporis, natus hic, doloribus repellat quae porro, tenetur minima odio nisi assumenda deserunt ratione at culpa. Maiores totam adipisci enim, at iure pariatur! Atque doloremque delectus laboriosam excepturi maiores amet accusantium quo. Laudantium, illum? Distinctio nostrum esse recusandae dolorem doloremque officia explicabo quisquam, eum odio! Dolore dolorum est distinctio ipsum esse quisquam facilis eos numquam a placeat aut beatae accusantium, repudiandae, iure molestias totam illum, quam ut ducimus. Est vero doloremque ratione laborum ex omnis dolorem pariatur aperiam atque, quas dolores, nisi inventore asperiores architecto beatae, quia placeat repellendus nobis eaque qui! Sint, consequuntur quasi nihil aliquid exercitationem, voluptates error laudantium porro suscipit enim soluta repellat velit provident doloremque sequi obcaecati cum inventore hic dolorum amet ullam illum? Odit hic corrupti sed numquam officiis minus voluptate fuga, repudiandae consectetur nesciunt mollitia voluptatibus, id voluptatem harum placeat eos dolor quidem. Vel necessitatibus quasi sunt, repellendus itaque totam impedit deserunt dolorem, cum animi accusantium quidem? Quam modi quas ipsa repudiandae pariatur aut quis debitis repellat, aspernatur, eius dolorem sequi minima cum voluptatum reiciendis blanditiis deleniti quia?</p>
                <h2>Lorem, ipsum dolor.</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora impedit consectetur expedita repudiandae tempore repellendus vel! Perspiciatis ipsa aperiam velit asperiores expedita animi nam culpa dolorem unde soluta laborum repellat laboriosam, cum vitae, numquam labore maiores optio! Aspernatur consectetur odit qui neque, facilis a! Sapiente repudiandae, suscipit, autem vitae voluptate ipsum perferendis aut impedit dolorum consectetur aspernatur, expedita minima? Quasi laudantium modi provident alias dolorem enim ipsam, blanditiis impedit nihil fuga eligendi ex quae id tempore accusamus suscipit, nam rerum nisi. Minus architecto itaque distinctio numquam fugiat laboriosam consequatur necessitatibus iste in quis unde rerum qui illo, ullam adipisci natus neque quibusdam ipsum earum vero quod voluptates nostrum? Nisi modi nemo quasi sit illum eius ducimus quis sint placeat? Placeat sequi repellat iste dolore, vero doloribus facilis velit, molestias labore obcaecati repellendus, possimus cumque laudantium cupiditate accusamus ex dolores minima dolor sapiente. Rerum a porro eligendi debitis esse. Mollitia, ipsa?</p>
            </Content>
            <Footer />
        </div>
     );
}
 
export default Sobre;